/*
 * action types
 */

export const PERSON_CREATE_REQUEST = 'PERSON_CREATE_REQUEST';
export const PERSON_CREATE_SUCCESS = 'PERSON_CREATE_SUCCESS';
export const PERSON_CREATE_FAILURE = 'PERSON_CREATE_FAILURE';

export const PERSON_READ_REQUEST = 'PERSON_READ_REQUEST';
export const PERSON_READ_SUCCESS = 'PERSON_READ_SUCCESS';
export const PERSON_READ_FAILURE = 'PERSON_READ_FAILURE';

export const PERSON_UPDATE_REQUEST = 'PERSON_UPDATE_REQUEST';
export const PERSON_UPDATE_SUCCESS = 'PERSON_UPDATE_SUCCESS';
export const PERSON_UPDATE_FAILURE = 'PERSON_UPDATE_FAILURE';

export const PERSON_DELETE_REQUEST = 'PERSON_DELETE_REQUEST';
export const PERSON_DELETE_SUCCESS = 'PERSON_DELETE_SUCCESS';
export const PERSON_DELETE_FAILURE = 'PERSON_DELETE_FAILURE';

export const PERSON_SEARCH_REQUEST = 'PERSON_SEARCH_REQUEST';
export const PERSON_SEARCH_SUCCESS = 'PERSON_SEARCH_SUCCESS';
export const PERSON_SEARCH_FAILURE = 'PERSON_SEARCH_FAILURE';
