/*
 * action types
 */

export const PERSON_FILTER_BY_NAME = 'PERSON_FILTER_BY_NAME';
export const PERSON_FILTER_TEAM = 'PERSON_FILTER_TEAM';
export const PERSON_FILTER_NO_TEAM = 'PERSON_FILTER_NO_TEAM';

